### ISSUE TITLE
Feature suggestion: automatically resend objects that failed to send to cloud

### ISSUE THREAD

**Issue by 5ource** [realms-team/solmanager#110]
I had problems running the request to resend. The script froze when the backup file is too big.
Suggestion:
When no internet access: store unsent objects in temporary file (as well as main backup file)
When internet established again: read unsent objects and send them to the server (then delete sent ones)

**Comment by keomabrun** [comment]
There was a problem when sending large amount of data (http max size or timeout I suppose). This is solve in the new release: https://github.com/realms-team/solmanager/issues/92
