### ISSUE TITLE
pip error with cffi

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#113]
To fix this issue, run apt-get install libffi-dev (first update: `apt-get update`)

```
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabi-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cffi
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-FqBldG/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-auZTKW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-FqBldG/cffi/
```

**Comment by keomabrun** [comment]
This above solution did not work on a RaspberryPi. I had to use the following:  
`sudo pip install -U cffi`

**Comment by keomabrun** [comment]
This is fixed by NOT installing the pyopenssl pip requirement. (uncomment in the requirement.txt file)
In the Metronome, `pyOpenSSL==0.14` seem to be sufficient while the `requirements.txt` says `pyopenssl>=17.0.0`
Question: are pyopenssl and pyOpenSSL different ?

**Comment by twatteyne** [comment]
I have idea :-(
