### ISSUE TITLE
HDLC error wrong packetId

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#117]
This happen in Grizzly solmanager CLI.
Solmanager: 1.1.0.0
Sol: 0.0.0.6
```
@Hdlc: Connection Error: wrong packetId
@Hdlc: Connection Error: wrong packetId
@Hdlc: Connection Error: wrong packetId
@Hdlc: Connection Error: wrong packetId
@Hdlc: Connection Error: unexpected response
```

**Comment by keomabrun** [comment]
It seems that the getMoteConfig runs in circle causing the snapshot process to run indefinitely. When I put traces I can see that it goes from mote 1 to 39 and then loops over the last three motes it never raises APIerror.

**Comment by twatteyne** [comment]
I understand you comment, but how does it relate to the title of this issue?

**Comment by keomabrun** [comment]
Those two seem to happen at the same time but you are right it might not be related. I will open another issue.
