### ISSUE TITLE
_cb_resend_POST

### ISSUE THREAD

**Issue by twatteyne** [realms-team/solmanager#12]

**Comment by keomabrun** [comment]
As the solmanager is not always accessible from internet, it should periodically request the server for actions such as: "Do I need to resend data (and which one)?"

**Comment by 5ource** [comment]
@keomabrun so the idea was that during an interval of time, data will not be sent to the server because the manager is unable to establish a connection. Once the connection is established again, the server should be able to request a re-attempt to send the unsent data. I saw the json post command for that is already implemented. The time extraction from the solmanager.backup file seems to be also implemented in sol. (great job!) I think what's left is to call the function in sol from the json post callback.

**Comment by keomabrun** [comment]
I does work now. I have to test it on our lab deployment though.
What's left is to automate the process, that is, to have the server automatically detect missing data and trigger the resending process. Do we want that ?

**Comment by twatteyne** [comment]
I propose we don't automate for now. What exactly needs to happen when the server wants to manager to resend the data between two timestamps?

**Comment by keomabrun** [comment]
Someone has to send a POST message to resend.json with the correct body message and token in the header. I followed the description in the solmanager README.

**Comment by keomabrun** [comment]
I just tested it and it works well !

**Comment by twatteyne** [comment]
Can we always address the manager directly on all deployments, i.e. is it not behind NAT?

**Comment by keomabrun** [comment]
This is another feature indeed. Should I that in the solmanager<---solsever pull possibility ?

**Comment by twatteyne** [comment]
I think we should wait for a definitive answer from the Berkeley team. If there is direct connection, much better.

**Comment by 5ource** [comment]
In all deployments of the American river, we can directly access the
manager (in case 2 managers were connected to the same modem, we used port
forwarding), and the Feather river should be the same, so I think a  post
form the server should work perfectly. Let me know if it's ready and I'll
test it from my side as well.

On Wed, Jun 15, 2016 at 8:22 AM, Thomas Watteyne <notifications@github.com>
wrote:

> I think we should wait for a definitive answer from the Berkeley team. If
> there is direct connection, much better.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/realms-team/solmanager/issues/12#issuecomment-226221706>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI6g7bVDHWkSl1UlCwqB35mdbFp8Cqypks5qMBitgaJpZM4Fr1K1>
> .
>



-- 
Sami Andrew Malek
PhD Student, Department of Civil and Environmental Engineering
621 Sutardja Dai Hall (CITRIS Building)
UC Berkeley, CA 94720-1758
sami.malek@berkeley.edu

**Comment by keomabrun** [comment]
I should work with the develop branch without any problem.
One thing though is the certificate, as it is self signed, the client that you will use to send queries to the solmanager has to validate the certificate.
I first connected to the solmanager using direct https to get the certificate validation page in my browser (Firefox) and then used a plugin (HttpRequester) for the queries.

Let me know if you need more precisions.
