### ISSUE TITLE
Measure Data consumption

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#123]
We have no idea of the amount of data required by the new version of SolSystem that uses Bluemix.
We should also measure the amount of traffic when using remote access (SSH).

**Comment by keomabrun** [comment]
Results after one day at SmartMarina
"""
 day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
      09/28/17     16.09 MiB |   30.12 MiB |   46.22 MiB |    5.46 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated        19 MiB |      37 MiB |      56 MiB |

"""

**Comment by keomabrun** [comment]
30MiB = 31.4MB. That's A LOT for one day.
Note that I played with SSH that same day.

**Comment by keomabrun** [comment]
Bad news. Last three days. Its even worst.
Note that the 28th of September that I've pushed earlier is different as the measure was taken in the middle of the 28th day.

```
         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
      09/28/17     21.72 MiB |   40.36 MiB |   62.08 MiB |    5.89 kbit/s
      09/29/17     28.29 MiB |   52.36 MiB |   80.65 MiB |    7.65 kbit/s
      09/30/17     28.40 MiB |   51.93 MiB |   80.33 MiB |    7.62 kbit/s
     ------------------------+-------------+-------------+---------------
```

**Comment by keomabrun** [comment]
When the big presentation is over, I will run the same tests without solmanager running.

**Comment by keomabrun** [comment]
Last 7 days at the smartmarina:
```
         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
      09/28/17     21.72 MiB |   40.36 MiB |   62.08 MiB |    5.89 kbit/s
      09/29/17     28.29 MiB |   52.36 MiB |   80.65 MiB |    7.65 kbit/s
      09/30/17     28.40 MiB |   51.93 MiB |   80.33 MiB |    7.62 kbit/s
      10/01/17     28.70 MiB |   53.50 MiB |   82.20 MiB |    7.79 kbit/s
      10/02/17     28.40 MiB |   53.63 MiB |   82.02 MiB |    7.78 kbit/s
      10/03/17     43.89 MiB |   55.00 MiB |   98.90 MiB |    9.38 kbit/s
      10/04/17     28.87 MiB |   54.33 MiB |   83.20 MiB |    7.89 kbit/s
```

**Comment by keomabrun** [comment]
I am now running a RaspberryPi without the solmanager to see how much the system itself consumes.

**Comment by keomabrun** [comment]
Last 4 days on a raw Raspberry Pi:
```
         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
      10/06/17      6.91 MiB |     275 KiB |    7.18 MiB |    0.68 kbit/s
      10/07/17      6.76 MiB |     266 KiB |    7.02 MiB |    0.67 kbit/s
      10/08/17      6.70 MiB |     277 KiB |    6.97 MiB |    0.66 kbit/s
      10/09/17      6.84 MiB |     276 KiB |    7.11 MiB |    0.67 kbit/s

```

**Comment by keomabrun** [comment]
I've enabled "Usage Monitoring" on BucksLake cellular modem. It give last day and month consumption. Last day was 77MB. We have to wait for a few weeks to have the monthly consumption.

This results corresponds to the one we have in the marina.
SolManager v1.2.1.0 with Bluemix MQTT is running on BuckLake.

**Comment by twatteyne** [comment]
are we going to run out of data? If yes, let's switchj off the Bluemix backend, and just to JsonServer for now

**Comment by keomabrun** [comment]
@5ource, do you know the cellular data limit ?
