### ISSUE TITLE
Implement a connector layer

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#129]
The connector layer should be a class with the following public functions:
- `publish`
- `subscribe`

Here is a list of potential connectors:
- `MQTT`
- `HTTP`
- `WebSocket`
- `File`

In case of `HTTP`, the `subscribe` function will start a thread that periodically pulls commands from the server.
In case of `File` the `subscribe` function will do nothing.

In case of `MQTT`, the `publish` function should start a private `connect` function if no connection was already established.

Each connector will have its own message queue.

To configure the connectors, a configuration file (YAML?) will define per connector:
- the connector type (MQTT, HTTP....)
- the publish rate
- the destination address or hostname (default to `api.solsystem.io`)
- the port
- the token/password

**Comment by twatteyne** [comment]
You're mixing up the interface of the class with the implementation. How it transaltes to MQTT, etc should come as a second step. First yuou need to completely define the interface of the class. For example, once I subscribe, how do I receive the data?

No YAML, please, just k=v in a file is more than enough

**Comment by keomabrun** [comment]
> For example, once I subscribe, how do I receive the data?

Sorry I made a mistake. I fixed the `subscribe` lines.
* For HTTP, a thread starts and poll the server periodically, for each message call the cb function
* For MQTT, default behaviour (handled by the paho-mqtt or ibmiot lib and call a cb function)
* For File, `subscribe` does nothing

So the top class definition will look like:
```python
class Connector():

    def __init__(self, config):
        # save config

    def _connect(self):        
        # connect if necessary

    def subscribe(self, cb):
        if self.connected:
            self.connected = self._connect()
        # subscribe

    def publish(self, obj):
        # publish
```

For each connection present in the config file, solmanager will start a `Connector` instance.

> No YAML, please, just k=v in a file is more than enough

As we need per-connector, with cannot just do k=v. We can do sections ? This works very well with https://docs.python.org/2/library/configparser.html

```
[connector1]
type=mqtt
host=api.solsystem.io
...

[connector2]
type=http
host=api.solsystem.io
```

**Comment by twatteyne** [comment]
In the `subscribe()` method, do I subscribe to everything all the time, i.e. not quantifier?

In the `publish()` method, please specify what params to pass. Putting `obj` is NOT OK, we are trying define the interface.

Please remove the `_connect()` method, that's internal. I'm only looking for any public methods, exactly what parameters are passed, and exactly what it does.

**Comment by twatteyne** [comment]
About the config file, please provide an enable config file, with all the configuration switches.

**Comment by keomabrun** [comment]
New spec here: https://github.com/realms-team/solmanager/tree/develop_129/connectors

**Comment by keomabrun** [comment]
up
