### ISSUE TITLE
Add backup server configuration

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#67]
In case the first solserver address is unreachable, the solmanager could send its data to a backup solserver.
Data synchronization will then be done between servers (InfluxDB clusters).

**Comment by twatteyne** [comment]
@keomabrun, we would use this setup between Berkeley and Paris, i.e. rather than choosing where to send the data to, we just have to sites with sync through an InfluxDB cluster.

**Comment by keomabrun** [comment]
We don't need this if we use a db on bluemix
