### ISSUE TITLE
Add resend number limitation

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#68]
Add a limitation to the number of object the solmanager can send after a "resend" request.
Otherwise a simple resend command could lead to a DoS.

**Comment by twatteyne** [comment]
Hmm. I believe the right thing to do is to properly authenticate the requestor to avoid DoS.
But there is still a danger of a false manipulation. You could limit the number of datapoints to 1000 or so, and have the requesting entity ask again and again if more are needed.
Again, more as a precaution against errors than a security feature.

**Comment by keomabrun** [comment]
Exactly !
