### ISSUE TITLE
Logging level inside configuration file

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#73]
We should be able to set the  Logging level in the solmanager.config file.

**Comment by twatteyne** [comment]
I'm not sure that's worth the effort. The loglevel should be set by a file, but that can be a file different from `solmanager.config`. Building a solution which allows for both configurations to be in the same file is IMO overkill.

**Comment by keomabrun** [comment]
Agreed. We can do that in logging.conf. I forgot.

Thanks.
