### ISSUE TITLE
solmanager on the MS basestation crash

### ISSUE THREAD

**Issue by 5ource** [realms-team/solmanager#80]
CLI Python output:

```
@Hdlc: Connection Error: Unexpected manager_hello
Connecting to /dev/ttyS4... PASS.
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
@Hdlc: Connection Error: Queue overflowed
```

Killed

CLI:

```
56219306 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'                   
64484805 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'                   
69213265 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
69249937 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
78229656 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
78871016 : Path Alarm #5-#24                                                            
79619952 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'                   
80011203 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'                   
82164095 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'                   
85429745 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
89574711 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
90544495 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
94075033 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'                   
95086585 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
96661765 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
100107908 : Path Alarm #2-#24
101155577 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'

102080148 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
104314026 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
105207721 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
105761466 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
106162916 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
106333619 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
107062969 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
107454235 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
108026483 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
121707202 : Path Alarm #5-#24
69835560 : Path Alarm #2-#24
68363915 : Path Alarm #2-#24
2095104 : Path Alarm #12-#35
PF: n=8 0 t=-1683804608 lh=-1685773060 d=1968452
79686372 : Path Alarm #1-#8
PF: n=10 0 t=-1683259526 lh=-1685229545 d=1970019
79703005 : Path Alarm #1-#10
```

**Comment by keomabrun** [comment]
@5ource, can you give us more information about this error ? Where/How did you get it ?

**Comment by 5ource** [comment]
This was the manager output at Buckslake after it stopped sending.
Also Kettle manager gave the following error:
cli output:
68192337 : MNGR_ERR_PKTLENGTH Unexpected packet length 068193323 : MNGR_ERR_P1

Fault
R0 = 0
R1 = 22
R2 = 2000355c
R3 = 0
R12 = 1
LR = 46027
PC = 4602c
PSR = 21000200
BFAR = 10100
CFSR = 8200
HFSR = 40000000
DFSR = 0
AFSR = 0
MFAR = 10100
IPSR = 415803
NVIC_ACTIVE0_R = 0
NVIC_ACTIVE1_R = 0
NVIC_SYS_HND_CTRL_R = 70000
SP = 20003508
Time = 8541879c

Fault
R0 = 1
R1 = 40000804
R2 = 8539b0a4
R3 = 8539b0a5
R12 = 27
LR = 59803
PC = c92f4
PSR = 61000003
BFAR = 10100
CFSR = 8200
HFSR = 40000000
DFSR = 0
AFSR = 0
MFAR = 10100                                                                    
IPSR = 415002
NVIC_ACTIVE0_R = 0
NVIC_ACTIVE1_R = 0
NVIC_ACTIVE1_R = 0
NVIC_SYS_HND_CTRL_R = 70000
SP = 20000898

Maybe it helps debugging the problem.

**Comment by twatteyne** [comment]
@5ource, why do you think those two are related. What versions of the manager is running? Are "Buckslake" and "Kettle" two different sites? Is it strictly the same error (I very much doubt so)?

**Comment by 5ource** [comment]
@twatteyne yea they are different sites. (should double check manager version).
I agree it seems a different issue, gonna create a new issue and remove this from here.

**Comment by twatteyne** [comment]
thanks

**Comment by keomabrun** [comment]
I can see we have the same error on the PEACH deployment when we run the last development versions.
Solmanager: https://github.com/realms-team/solmanager/commit/ef31d780421bfa0776093795a3907d3bf4eea2e6
Sol https://github.com/realms-team/sol/commit/e6cb535d0bd55c8d5f34127c349987434ab53bde

**Comment by keomabrun** [comment]
TODO: check running thread from python after it crashed.

**Comment by 5ource** [comment]
setting the isReliable parameter for the connector in python seems to prevent the script from failing (by disregarding other failures most probably).

**Comment by keomabrun** [comment]
is the error still present on the version 1.0.0.0 ?

**Comment by 5ource** [comment]
I deployed 1.0.0.0 at the sites. Will let you know if I encounter it again.

**Comment by keomabrun** [comment]
:+1:  super !

**Comment by twatteyne** [comment]
yaaay!

**Comment by keomabrun** [comment]
@5ource, did you encounter this error again ?

**Comment by twatteyne** [comment]
what is MS?

**Comment by keomabrun** [comment]
Must be related to #119
