### ISSUE TITLE
ConnectionError should not crash the solmanager

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#88]
On sites with unstable connection, the manager keep on restarting and we loose data.

**Comment by twatteyne** [comment]
what do you mean by "unstable" connection?

**Comment by 5ource** [comment]
I think when manager cannot establish an internet connection to the server.

**Comment by keomabrun** [comment]
Sorry I forgot to mention that this is related to thread #86 .
I've just looked at the code and the Requests module exceptions are not properly caught.

The code is currently catching requests.exceptions when it should catch requests.exceptions.RequestException
See
http://docs.python-requests.org/en/latest/user/quickstart/#errors-and-exceptions
