### ISSUE TITLE
interface to http optionally

### ISSUE THREAD

**Issue by twatteyne** [realms-team/solmanager#93]
add `--connect-through-JsonServer` option
* without the option, the SolManager connects to the serial port of the manager
* with the option, the SolManager connect to the manager over a `JsonServer` instance

**Comment by keomabrun** [comment]
@twatteyne can you confirm this is solved by the field `managerconnectionmode` in the configuration file ?

**Comment by keomabrun** [comment]
@twatteyne up ?

**Comment by twatteyne** [comment]
I agree the use of a config file replaces this switch, which should now be removed

**Comment by keomabrun** [comment]
This option was never implemented so I close the issue.
https://github.com/realms-team/solmanager/blob/master/solmanager.py#L1054
